[package]
name = "gitoken"
version = "0.0.1"
authors = ["Brandon Sanderson <bas.bsanders@gmail.com>"]

[dependencies]
rustc-serialize = "*"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
